/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_helix_Server */

#ifndef _Included_org_helix_Server
#define _Included_org_helix_Server
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: handlerStatic */
/*
 * Class:     org_helix_Server
 * Method:    create
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_helix_Server_create
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_helix_Server
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_helix_Server_start
  (JNIEnv *, jobject);

/*
 * Class:     org_helix_Server
 * Method:    test
 * Signature: (Lorg/helix/Request;Lorg/helix/Response;)V
 */
JNIEXPORT void JNICALL Java_org_helix_Server_test
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_helix_Server
 * Method:    test1
 * Signature: ()Ljava/util/Map$Entry;
 */
JNIEXPORT jobject JNICALL Java_org_helix_Server_test1
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
